### PR TITLE
Remove unused SimpleDispatcher

### PR DESCRIPTION
**Pull request by jerith**
It hasn't been touched in several years and it appears to be the only thing that uses publishers with arbitrary routing keys.

### CODE REVIEW

**Comment by hodgestar** [comment]
Looks good. There are also a reference to `SimpleDispatcher` in `etc/supervisord.smpp_test.conf` though.

**Comment by hodgestar** [comment]
Do we want to fix `config/smpp_test.yaml` and `config/smpp_test_http_post.yaml` so they have the same `transport _name` now that the dispatcher is gone?

**Comment by jerith** [comment]
No, because they're both transports. I think the stuff I removed was broken anyway.

**Comment by hodgestar** [comment]
Oh. :/

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
