### PR TITLE
Publish status event when starting for SMPP transport

### PR DESCRIPTION
**Pull request by justinvdm**
Similar to #983-#988, except for when we start connecting.

### CODE REVIEW

**Comment by justinvdm** [comment]
Publishing connecting events is going to require changing `ReconnectingClientService` to support hooks for when we connect. For now, I've renamed the ticket to be for publishing status events when the transport is starting. The plan is to add connect event publishing in a different PR once we are able to add hooks for when we are reconnecting.

**Comment by justinvdm** [comment]
Ready for review.

**Comment by rudigiesler** [comment]
:+1:

**Comment by rudigiesler** [comment]
But we must watch out for https://github.com/praekelt/vumi/pull/992 and this, we need to make sure that one lands before the other, and that the relevant changes are made in the other.

**Comment by justinvdm** [comment]
@rudigiesler thanks, merging in #992 and making the relevant changes. Will land once #992 lands.

**Pull request merged**
