### PR TITLE
Use new worker logger

### PR DESCRIPTION
**Pull request by rudigiesler**
Use the new worker logger for a few transports.

### CODE REVIEW

**Comment by rudigiesler** [comment]
Ready for review.

**Comment by jerith** [comment]
Some of the updated multiline log calls are probably pep8 violations.

**Comment by hodgestar** [comment]
Error from Travis:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/build/praekelt/vumi/vumi/transports/smpp/tests/test_protocol.py", line 332, in test_bind_transmitter
    protocol = yield self.get_protocol(bind_type='TX')
  File "/home/travis/build/praekelt/vumi/vumi/transports/smpp/tests/test_protocol.py", line 76, in get_protocol
    dummy_service = DummySmppService(self.clock, self.redis, cfg)
  File "/home/travis/build/praekelt/vumi/vumi/transports/smpp/tests/test_protocol.py", line 28, in __init__
    self, config.delivery_report_processor_config)
  File "/home/travis/build/praekelt/vumi/vumi/transports/smpp/processors/default.py", line 85, in __init__
    self.log = transport.log
exceptions.AttributeError: 'DummySmppService' object has no attribute 'log'
```

**Comment by rudigiesler** [comment]
Fixed the pep8 violations. Tests should also be fixed now.

**Comment by rudigiesler** [comment]
Ready for review again.

**Comment by hodgestar** [comment]
:+1: once Travis is happy. I restarted the failed test (it looks unrelated, but wasn't 100% sure).

**Pull request merged**
