### PR TITLE
Fix SMPP sequence number to message id TTL

### PR DESCRIPTION
**Pull request by jerith**
Like #968, but for the `sequence_number` key.

### CODE REVIEW

**Comment by jerith** [comment]
The ever-growing chain of callbacks on deletion is ugly, but this will be fixed in #965 and friends.

**Comment by smn** [comment]
:+1:

**Comment by smn** [comment]
At some point we're likely going to be able to do away with `third_party_id_expiry` entirely? We also probably want to trash the deprecated SMPP implementation at some point because that's going to be the only code still using that.

**Comment by hodgestar** [comment]
:+1:

**Comment by jerith** [comment]
> At some point we're likely going to be able to do away with `third_party_id_expiry` entirely?

Not if we want to be able to map delivery reports to vumi messages. The only thing still using it now is the `remote_id` to `message_id` mapping.

**Pull request merged**
